CPPFLAGS = -I$(HEADER_PATH)

LDFLAGS = -L$(LIBRARY_PATH)

LIBS = -lAFEPack 

CXXFLAGS = -O2 -g -fopenmp

CXX = mpicxx

main : poisson_equation.o
	$(CXX) -omain poisson_equation.o $(LDFLAGS) $(LIBS) $(CXXFLAGS)

clean:
	rm -f poisson_equation.o *~ u.dx D.[nse]
