CXXFLAGS:=-DDEAL_II_WITH_MPI $(CXXFLAGS)
LIBS:=-lAFEPack -lboost_serialization $(LIBS)
MPILIBS:=-lAFEPack_mpi $(LIBS)

TRILINOS_HOME=/usr/local/Trilinos
TRILINOS_INC=-I$(TRILINOS_HOME)/include
TRILINOS_LIBS=-lml -lifpack -laztecoo -lepetraext -lepetra -lteuchos -ltriutils -lblas -llapack -L$(TRILINOS_HOME)/lib

PETSC_DIR=/usr/local
PETSC_INC=-I$(PETSC_DIR)/include
PETSC_MPICC=$(MPICC)
PETSC_LIBS=-lpetsc -L$(PETSC_DIR)/lib -lX11 

HYPRE_MPICC=$(MPICC)
HYPRE_LIBS=-lHYPRE
