CPPFLAGS = -I$(HEADER_PATH)

LDFLAGS = -L$(LIBRARY_PATH)

LIBS = -lAFEPack 

CXXFLAGS = -O2 -g -fopenmp

CXX = mpicxx

source = $(wildcard *.cpp)
object = $(patsubst %.cpp, %.o, $(source))

all : main

%.o : %.cpp
	$(CXX) -c -o $@ $< $(LDFLAGS) $(LIBS) $(CXXFLAGS) $(CPPFLAGS)

main : $(object)
	$(CXX) -o $@ $(object) $(LDFLAGS) $(LIBS) $(CXXFLAGS) $(CPPFLAGS)

clean :
	-rm -rf $(object)
	-rm -rf main
	-rm -f *.[nes]
	-rm -f *.dx

