#! /bin/sh

export AFEPACK_PATH=$HOME/src/AFEPack
if test x$LD_LIBRARY_PATH == x ; then
	LD_LIBRARY_PATH="$AFEPACK_PATH/library/lib"
else
	LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$AFEPACK_PATH/library/lib" 
fi
export LD_LIBRARY_PATH
export AFEPACK_TEMPLATE_PATH="$AFEPACK_PATH/template/triangle:$AFEPACK_PATH/template/twin_triangle"

exec ./main $*
