#! /bin/sh

BASEDIR=$(dirname "$0")

export AFEPACK=$BASEDIR/../include/AFEPack
export AFEPACK_TEMPLATE_PATH=$AFEPACK/template/tetrahedron
export LD_LIBRARY_PATH=$BASEDIR/../lib:$LD_LIBRARY_PATH
$BASEDIR/gmsh2mesh.bin $*

