CXX=mpicxx

CPPFLAGS = -I$(HEADER_PATH)
LDFLAGS = -L$(LIBRARY_PATH)
LIBS=-lAFEPack 
CXXFLAGS=-O2 -fopenmp

main : main.cpp EllipticEquation.o
	$(CXX) $(CXXFLAGS) main.cpp EllipticEquation.o $(CPPFLAGS) $(LDFLAGS) $(LIBS) -omain

clean :
	rm -f main *~ *.[nes] u.dx *.o
